name: Test workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  print_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo This is test first action
